### ISSUE TITLE
Chips lost '+x' permission after being auto-upgraded

### ISSUE THREAD

**Issue by simnalamburt** [kinoru/chips#23]
### How to reproduce this error

![image](https://cloud.githubusercontent.com/assets/4435445/19800087/17888016-9d35-11e6-8e8a-060965b0baab.png)
### How to fix it

https://github.com/xtendo-org/chips/blob/master/src/SelfUpdate.hs#L67

``` haskell
runUpdate repo tag assetName path = getAsset >>= \case
    Right bin -> bracket topen hClose $ \ h -> do
        B.hPut h bin
        hClose h
        rename tmpPath path
        return $ Right tag
    Left err -> return $ Left err
```

Maybe we should call `chmod +x path` thing after `rename tmpPath path`

**Comment by xtendo-org** [comment]
Fixed in 36ca3dc

Thanks for reporting!
