### ISSUE TITLE
Running chips should reload the configuration

### ISSUE THREAD

**Issue by xtendo-org** [kinoru/chips#6]
Currently running chips is not sufficient to update the plugin system; it doesn't load the new plugins to the current fish shell which ran chips. The shell will remain unchanged.

Let's say the desired use-case scenario is that the user types `chips`, then the install/update takes place, and the current shell is loaded with the latest configuration and plugins. This means:
- The executable file needs to call the `exec*` family of functions to replace itself with fish.
- Fish needs to execute chips by `exec chips`, not just `chips`.

So, we need to add, at the end of the chips source code, a line that calls `exec*`. Then, in the `build.fish` file, something like below:

``` fish
alias chips "exec ~/.local/bin/chips"
```

Alternatively, we can simply drop the line below in `build.fish`:

``` fish
alias chips "~/.local/bin/chips; exec fish"
```

**Comment by simnalamburt** [comment]
I really like the second option. With this, I don't even need to add the `~/.local/bin` to my `$PATH` variable!

``` fish
alias chips "~/.local/bin/chips; and exec fish"
```
