### ISSUE TITLE
bug: Chips deletes all the plugins when executed offline

### ISSUE THREAD

**Issue by heejongahn** [kinoru/chips#8]
When a user tries to update/install plugins without internet connection, something like this happens:

``` bash
chips: fish plugin manager
version 1.0.0
Checking update for theme-bobthefish...
Checking update for fish-sensible...
Failed checking update for fish-sensible.
Failed checking update for theme-bobthefish.
Build result saved at /Users/nobell/.config/chips/build.fish
```

As (failed) build result is saved at `build.fish`, it deletes (some of) existing plugins. For this case, `theme-bobthefish` survived but `fish-sensible` didn't. Maybe just popping out the error message and doing nothing (or just prune unused plugins) when offline would do the trick?

**Comment by xtendo-org** [comment]
This is indeed a bug. Thank you very much for the report!
